FROM node:25-slim

ARG VITE_HTTP_BASIC_AUTH_EXPECTED_VALUE
ARG VITE_SQLITE_DB_FILE_PATH
ENV VITE_HTTP_BASIC_AUTH_EXPECTED_VALUE=${VITE_HTTP_BASIC_AUTH_EXPECTED_VALUE}
ENV VITE_SQLITE_DB_FILE_PATH=${VITE_SQLITE_DB_FILE_PATH}

ADD . /app
WORKDIR /app

RUN npm install
RUN npm run build

CMD node ./build/index.js
